"""migracao inicial

Revision ID: 6ca2a56a7b76
Revises: 
Create Date: 2025-11-11 15:36:13.957910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca2a56a7b76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logradouros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('unidade', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('localidade', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('regiao', sa.String(length=255), nullable=True),
    sa.Column('ibge', sa.Integer(), nullable=True),
    sa.Column('gia', sa.Integer(), nullable=True),
    sa.Column('ddd', sa.Integer(), nullable=True),
    sa.Column('siafi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cep'], ['logradouros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('logradouros')
    # ### end Alembic commands ###
